apiVersion: v1
kind: Service
metadata:
  name: QuestionShow-prod-svc
  labels:
    app: QuestionShow
    environment: production
spec:
  selector:
    app: QuestionShow
    environment: production
  ports:
  - port: 80 
    targetPort: 8080
    nodePort: 31101
  type: "NodePort"      
